//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASQSE
    {
        public int ASQSEPK { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Editor { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public System.DateTime FormDate { get; set; }
        public bool HasDemographicInfoSheet { get; set; }
        public bool HasPhysicianInfoLetter { get; set; }
        public int TotalScore { get; set; }
        public int ChildFK { get; set; }
        public int IntervalCodeFK { get; set; }
        public int ProgramFK { get; set; }
        public int Version { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual CodeASQSEInterval CodeASQSEInterval { get; set; }
        public virtual Program Program { get; set; }
    }
}
