//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOQCWLTView
    {
        public int BenchmarkOfQualityCWLTPK { get; set; }
        public System.DateTime FormDate { get; set; }
        public int HubFK { get; set; }
        public string HubName { get; set; }
        public string StateName { get; set; }
        public string TeamMembers { get; set; }
    }
}
