//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildStatus
    {
        public int ChildStatusPK { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Editor { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public System.DateTime StatusDate { get; set; }
        public int ChildStatusCodeFK { get; set; }
        public int ChildFK { get; set; }
        public int ProgramFK { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual CodeChildStatus CodeChildStatus { get; set; }
        public virtual Program Program { get; set; }
    }
}
