//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeLCLResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CodeLCLResponse()
        {
            this.LCLResponse = new HashSet<LCLResponse>();
            this.LeadershipCoachLog = new HashSet<LeadershipCoachLog>();
            this.LeadershipCoachLog1 = new HashSet<LeadershipCoachLog>();
        }
    
        public int CodeLCLResponsePK { get; set; }
        public string Abbreviation { get; set; }
        public string Description { get; set; }
        public string Group { get; set; }
        public int OrderBy { get; set; }
        public string FieldName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LCLResponse> LCLResponse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadershipCoachLog> LeadershipCoachLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadershipCoachLog> LeadershipCoachLog1 { get; set; }
    }
}
