//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CodeForm()
        {
            this.CodeProgramRolePermission = new HashSet<CodeProgramRolePermission>();
            this.FormDueDate = new HashSet<FormDueDate>();
            this.FormSchedule = new HashSet<FormSchedule>();
        }
    
        public int CodeFormPK { get; set; }
        public bool AllowDueDate { get; set; }
        public bool DisplayOnHelpPage { get; set; }
        public string FormAbbreviation { get; set; }
        public string FormName { get; set; }
        public int OrderBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodeProgramRolePermission> CodeProgramRolePermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormDueDate> FormDueDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormSchedule> FormSchedule { get; set; }
    }
}
