//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeTeamPosition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CodeTeamPosition()
        {
            this.CoachingCircleLCMeetingDebriefTeamMember = new HashSet<CoachingCircleLCMeetingDebriefTeamMember>();
            this.CWLTMemberRole = new HashSet<CWLTMemberRole>();
            this.PLTMemberRole = new HashSet<PLTMemberRole>();
            this.SLTMemberRole = new HashSet<SLTMemberRole>();
        }
    
        public int CodeTeamPositionPK { get; set; }
        public string Abbreviation { get; set; }
        public string Description { get; set; }
        public int OrderBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoachingCircleLCMeetingDebriefTeamMember> CoachingCircleLCMeetingDebriefTeamMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CWLTMemberRole> CWLTMemberRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLTMemberRole> PLTMemberRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SLTMemberRole> SLTMemberRole { get; set; }
    }
}
