//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeProgramRolePermission
    {
        public int CodeProgramRolePermissionPK { get; set; }
        public bool AllowedToAdd { get; set; }
        public bool AllowedToDelete { get; set; }
        public bool AllowedToEdit { get; set; }
        public bool AllowedToView { get; set; }
        public bool AllowedToViewDashboard { get; set; }
        public int CodeFormFK { get; set; }
        public int CodeProgramRoleFK { get; set; }
    
        public virtual CodeForm CodeForm { get; set; }
        public virtual CodeProgramRole CodeProgramRole { get; set; }
    }
}
