//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CWLTMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CWLTMember()
        {
            this.BOQCWLTParticipant = new HashSet<BOQCWLTParticipant>();
            this.CWLTActionPlan = new HashSet<CWLTActionPlan>();
            this.CWLTMemberAgencyAssignment = new HashSet<CWLTMemberAgencyAssignment>();
            this.CWLTMemberRole = new HashSet<CWLTMemberRole>();
            this.HubLCMeetingDebriefSessionAttendee = new HashSet<HubLCMeetingDebriefSessionAttendee>();
        }
    
        public int CWLTMemberPK { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Editor { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string EmailAddress { get; set; }
        public string FirstName { get; set; }
        public string GenderSpecify { get; set; }
        public string IDNumber { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> EthnicityCodeFK { get; set; }
        public Nullable<int> GenderCodeFK { get; set; }
        public Nullable<int> HouseholdIncomeCodeFK { get; set; }
        public Nullable<int> RaceCodeFK { get; set; }
        public int HubFK { get; set; }
        public string PhoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOQCWLTParticipant> BOQCWLTParticipant { get; set; }
        public virtual CodeEthnicity CodeEthnicity { get; set; }
        public virtual CodeGender CodeGender { get; set; }
        public virtual CodeHouseholdIncome CodeHouseholdIncome { get; set; }
        public virtual CodeRace CodeRace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CWLTActionPlan> CWLTActionPlan { get; set; }
        public virtual Hub Hub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CWLTMemberAgencyAssignment> CWLTMemberAgencyAssignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CWLTMemberRole> CWLTMemberRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HubLCMeetingDebriefSessionAttendee> HubLCMeetingDebriefSessionAttendee { get; set; }
    }
}
