//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CWLTActionPlanChanged
    {
        public int CWLTActionPlanChangedPK { get; set; }
        public System.DateTime ChangeDatetime { get; set; }
        public string ChangeType { get; set; }
        public string Deleter { get; set; }
        public int CWLTActionPlanPK { get; set; }
        public System.DateTime ActionPlanEndDate { get; set; }
        public System.DateTime ActionPlanStartDate { get; set; }
        public string AdditionalNotes { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Editor { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsLeadershipCoachInvolved { get; set; }
        public string MissionStatement { get; set; }
        public string LeadershipCoachUsername { get; set; }
        public int HubCoordinatorFK { get; set; }
        public int HubFK { get; set; }
        public bool IsPrefilled { get; set; }
        public bool ReviewedActionSteps { get; set; }
        public bool ReviewedBasicInfo { get; set; }
        public bool ReviewedGroundRules { get; set; }
    }
}
