//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormSchedule
    {
        public int FormSchedulePK { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Editor { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool ScheduledForJan { get; set; }
        public bool ScheduledForFeb { get; set; }
        public bool ScheduledForMar { get; set; }
        public bool ScheduledForApr { get; set; }
        public bool ScheduledForMay { get; set; }
        public bool ScheduledForJun { get; set; }
        public bool ScheduledForJul { get; set; }
        public bool ScheduledForAug { get; set; }
        public bool ScheduledForSep { get; set; }
        public bool ScheduledForOct { get; set; }
        public bool ScheduledForNov { get; set; }
        public bool ScheduledForDec { get; set; }
        public int ScheduleYear { get; set; }
        public Nullable<int> ClassroomFK { get; set; }
        public int CodeFormFK { get; set; }
        public int ProgramFK { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual CodeForm CodeForm { get; set; }
        public virtual Program Program { get; set; }
    }
}
