//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCLTeamMemberEngagement
    {
        public int LCLTeamMemberEngagementPK { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int LeadershipCoachLogFK { get; set; }
        public int PLTMemberFK { get; set; }
    
        public virtual LeadershipCoachLog LeadershipCoachLog { get; set; }
        public virtual PLTMember PLTMember { get; set; }
    }
}
