//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCMeetingDebriefView
    {
        public string CustomViewPK { get; set; }
        public int MeetingDebriefPK { get; set; }
        public string MeetingDebriefType { get; set; }
        public string TeamDescription { get; set; }
        public string CohortName { get; set; }
        public int DebriefYear { get; set; }
        public string LocationAddress { get; set; }
        public string PrimaryContactEmail { get; set; }
        public string PrimaryContactPhone { get; set; }
        public string LeadershipCoachUsername { get; set; }
        public Nullable<int> ProgramFK { get; set; }
        public Nullable<int> HubFK { get; set; }
        public int StateFK { get; set; }
        public string StateName { get; set; }
    }
}
