//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadershipCoachLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeadershipCoachLog()
        {
            this.LCLInvolvedCoach = new HashSet<LCLInvolvedCoach>();
            this.LCLResponse = new HashSet<LCLResponse>();
            this.LCLTeamMemberEngagement = new HashSet<LCLTeamMemberEngagement>();
        }
    
        public int LeadershipCoachLogPK { get; set; }
        public string ActNarrative { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> CyclePhase { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string Editor { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string HighlightsNarrative { get; set; }
        public bool IsComplete { get; set; }
        public Nullable<bool> IsMonthly { get; set; }
        public Nullable<int> NumberOfAttemptedEngagements { get; set; }
        public Nullable<int> NumberOfEngagements { get; set; }
        public string OtherDomainTwoSpecify { get; set; }
        public string OtherEngagementSpecify { get; set; }
        public string OtherSiteResourcesSpecify { get; set; }
        public string OtherTopicsDiscussedSpecify { get; set; }
        public string OtherTrainingsCoveredSpecify { get; set; }
        public Nullable<int> TargetedTrainingHours { get; set; }
        public Nullable<int> TargetedTrainingMinutes { get; set; }
        public string ThinkNarrative { get; set; }
        public Nullable<int> TotalDurationHours { get; set; }
        public Nullable<int> TotalDurationMinutes { get; set; }
        public Nullable<int> GoalCompletionLikelihoodCodeFK { get; set; }
        public string LeadershipCoachUsername { get; set; }
        public int ProgramFK { get; set; }
        public Nullable<int> TimelyProgressionLikelihoodCodeFK { get; set; }
    
        public virtual CodeLCLResponse GoalCompletionLikelihood { get; set; }
        public virtual CodeLCLResponse TimelyProgressionLikelihood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LCLInvolvedCoach> LCLInvolvedCoach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LCLResponse> LCLResponse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LCLTeamMemberEngagement> LCLTeamMemberEngagement { get; set; }
        public virtual Program Program { get; set; }
    }
}
