//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewsEntry()
        {
            this.NewsItem = new HashSet<NewsItem>();
        }
    
        public int NewsEntryPK { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Editor { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int NewsEntryTypeCodeFK { get; set; }
        public Nullable<int> ProgramFK { get; set; }
        public Nullable<int> HubFK { get; set; }
        public Nullable<int> StateFK { get; set; }
        public Nullable<int> CohortFK { get; set; }
    
        public virtual CodeNewsEntryType CodeNewsEntryType { get; set; }
        public virtual Cohort Cohort { get; set; }
        public virtual Hub Hub { get; set; }
        public virtual Program Program { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsItem> NewsItem { get; set; }
    }
}
