//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramChanged
    {
        public int ProgramChangedPK { get; set; }
        public System.DateTime ChangeDatetime { get; set; }
        public string ChangeType { get; set; }
        public string Deleter { get; set; }
        public int ProgramPK { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Editor { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> ProgramEndDate { get; set; }
        public string ProgramName { get; set; }
        public Nullable<System.DateTime> ProgramStartDate { get; set; }
        public int CohortFK { get; set; }
        public int HubFK { get; set; }
        public int StateFK { get; set; }
        public string IDNumber { get; set; }
    }
}
