//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportCatalog
    {
        public int ReportCatalogPK { get; set; }
        public string CriteriaOptions { get; set; }
        public string CriteriaDefaults { get; set; }
        public string DocumentationLink { get; set; }
        public string Keywords { get; set; }
        public string OptionalCriteriaOptions { get; set; }
        public string ReportCategory { get; set; }
        public string ReportClass { get; set; }
        public string ReportDescription { get; set; }
        public string ReportName { get; set; }
        public string RolesAuthorizedToRun { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
