//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLTActionPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SLTActionPlan()
        {
            this.SLTActionPlanActionStep = new HashSet<SLTActionPlanActionStep>();
            this.SLTActionPlanGroundRule = new HashSet<SLTActionPlanGroundRule>();
            this.SLTActionPlanMeeting = new HashSet<SLTActionPlanMeeting>();
        }
    
        public int SLTActionPlanPK { get; set; }
        public System.DateTime ActionPlanEndDate { get; set; }
        public System.DateTime ActionPlanStartDate { get; set; }
        public string AdditionalNotes { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Editor { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string MissionStatement { get; set; }
        public int StateFK { get; set; }
        public int WorkGroupFK { get; set; }
        public int WorkGroupLeadFK { get; set; }
        public Nullable<bool> IsFullyReviewed { get; set; }
        public bool IsPrefilled { get; set; }
        public bool ReviewedActionSteps { get; set; }
        public bool ReviewedBasicInfo { get; set; }
        public bool ReviewedGroundRules { get; set; }
    
        public virtual SLTMember SLTMember { get; set; }
        public virtual SLTWorkGroup SLTWorkGroup { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SLTActionPlanActionStep> SLTActionPlanActionStep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SLTActionPlanGroundRule> SLTActionPlanGroundRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SLTActionPlanMeeting> SLTActionPlanMeeting { get; set; }
    }
}
