//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFileUploadChanged
    {
        public int UserFileUploadChangedPK { get; set; }
        public System.DateTime ChangeDatetime { get; set; }
        public string ChangeType { get; set; }
        public string Deleter { get; set; }
        public int UserFileUploadPK { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Description { get; set; }
        public string DisplayFileName { get; set; }
        public string Editor { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string FileType { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> CohortFK { get; set; }
        public Nullable<int> HubFK { get; set; }
        public Nullable<int> ProgramFK { get; set; }
        public Nullable<int> StateFK { get; set; }
        public int TypeCodeFK { get; set; }
        public string UploadedBy { get; set; }
    }
}
